export const pricePlans = {
  title: 'Pricing plans for teams of all sizes',
  desc: "Choose an affordable plan that's packed with the best features for engaging your audience, creating customer loyalty, and driving sales.",
  plans: [
    {
      title: 'Freelancer',
      description: 'Ideal for individual professionals',
      price: 19.99,
      currency: 'USD',
      mostPopular: false,
      frequency: 'monthly',
      features: [
        { feature: '5 products' },
        { feature: 'Up to 1,000 subscribers' },
        { feature: 'Basic analytics' },
        { feature: '24/7 support' },
      ],
      cta: 'Start your trial!',
    },
    {
      title: 'Startup',
      description: 'Perfect for small businesses',
      price: 49.99,
      currency: 'USD',
      mostPopular: true,
      frequency: 'monthly',
      features: [
        { feature: '25 products' },
        { feature: 'Up to 10,000 subscribers' },
        { feature: 'Advanced analytics' },
        { feature: '24/7 support' },
        { feature: 'Marketing automation' },
      ],
      cta: 'Start your trial!',
    },
    {
      title: 'Enterprise',
      description: 'Tailored for large organizations',
      price: 99.99,
      currency: 'USD',
      mostPopular: false,
      frequency: 'monthly',
      features: [
        { feature: 'Unlimited products' },
        { feature: 'Unlimited subscribers' },
        { feature: 'Advanced analytics' },
        { feature: 'One-hour, dedicated support response time' },
        { feature: 'Marketing automation' },
        { feature: 'Salesforce, Clearbit Reveal & Marketo integrations' },
      ],
      cta: 'Start your trial!',
    },
  ],
}
